Repository hatchways/team-spartan, pull requests merged in 2021-05, with the labels that each got.

#34 Protected Routes Component and Cleaner Project Structure
  client/src/App.tsx
  client/src/context/index.ts
  client/src/context/useAuthContext.tsx
  client/src/routes.tsx
  client/src/routes/AuthRoute.tsx
  client/src/routes/ProtectedRoute.tsx
  client/src/unauthorized.tsx
Labels: Frontend, enhancement

#38 Create Contest Model with base properties
  server/models/Contest.ts
Labels: Backend, Week 1

#37 Signup/login
  client/.prettierrc
  client/package.json
  client/src/components/AuthHeader/useStyles.ts
  client/src/index.css
  client/src/interface/AuthApiData.ts
  client/src/interface/FetchOptions.ts
  client/src/interface/User.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/LoginForm/LoginForm.tsx
  client/src/pages/Login/LoginForm/useStyles.ts
  client/src/pages/Login/useStyles.ts
  client/src/pages/SignUp/SignUp.tsx
  client/src/pages/SignUp/SignUpForm/SignUpForm.tsx
  client/src/pages/SignUp/SignUpForm/useStyles.ts
  client/src/pages/SignUp/useStyles.ts
  client/src/setupTests.ts
  client/tsconfig.json
  client/yarn.lock
  server/app.js
  server/db.js
Labels: Frontend

#39 Add demo button and fix testing issues.
  client/src/pages/Login/Login.test.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/LoginForm/LoginForm.test.tsx
  client/src/pages/Login/LoginForm/LoginForm.tsx
  client/src/pages/Login/LoginForm/useStyles.ts
  client/src/pages/Login/useStyles.ts
Labels: Frontend
